import { useEffect, useMemo, useState } from 'react'
import { KeyRound, Lock, Search, ShieldQuestion, UserPlus, X } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { UserAction } from '@/lib/types'

export interface PendingSubRoleSetup { id: string; parentId: string; parentName: string; subRoleId: string; name: string }
type SelectedAction = UserAction | PendingSubRoleSetup
interface AdminPendingActionsProps { items: UserAction[]; onResolve: (item: UserAction) => void; subRoleSetups?: PendingSubRoleSetup[]; onConfigureSubRole?: (setup: PendingSubRoleSetup) => void }

function actionMeta(item: UserAction) {
  const isForgot = item.type === 'forgot-password'
  const isAccessReq = item.type === 'access-request'
  return { Icon: isAccessReq ? UserPlus : isForgot ? KeyRound : Lock, title: isAccessReq ? 'New Access Request' : isForgot ? 'Forgot Password Request' : 'Account Locked Out', label: isAccessReq ? 'Review & Create Account' : isForgot ? 'Generate Temp Password' : 'Unlock & Send Temp', tone: isAccessReq ? 'text-primary' : isForgot ? 'text-rose-500' : 'text-amber-500' }
}
function pendingAge(item: UserAction) {
  if (item.id === 'preview-account-locked-out' || item.id === 'preview-forgot-password') return 'Preview'
  if (!item.requestedAt) return null
  const requested = new Date(item.requestedAt)
  if (Number.isNaN(requested.getTime())) return null
  const today = new Date(); const start = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime()
  const days = Math.max(0, Math.floor((start(today) - start(requested)) / 86400000))
  return days === 0 ? 'Pending today' : `Pending for ${days} day${days === 1 ? '' : 's'}`
}

export function AdminPendingActions({ items, onResolve, subRoleSetups = [], onConfigureSubRole }: AdminPendingActionsProps) {
  const [selected, setSelected] = useState<SelectedAction | null>(null)
  const [showAll, setShowAll] = useState(false)
  const [search, setSearch] = useState('')
  const allItems = useMemo(() => [...subRoleSetups.map((item) => ({ ...item, kind: 'setup' as const })), ...items.map((item) => ({ ...item, kind: 'action' as const }))], [items, subRoleSetups])
  const previewItems = allItems.slice(0, 5)
  const isPreviewItem = (item: SelectedAction): item is UserAction => 'type' in item && (item.id === 'preview-account-locked-out' || item.id === 'preview-forgot-password')
  const isUserAction = (item: SelectedAction): item is UserAction => 'type' in item
  const filteredItems = allItems.filter((item) => { const q = search.trim().toLowerCase(); return !q || ('type' in item ? [actionMeta(item).title, item.email, item.user, item.accountType].filter(Boolean).join(' ').toLowerCase().includes(q) : [item.name, item.parentName, 'permission configuration'].join(' ').toLowerCase().includes(q)) })
  useEffect(() => { if (!selected && !showAll) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && (selected ? setSelected(null) : setShowAll(false)); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [selected, showAll])
  const runAction = (item: SelectedAction) => { if (isUserAction(item)) onResolve(item); else onConfigureSubRole?.(item); setSelected(null) }
  const row = (item: SelectedAction) => { const user = isUserAction(item); const meta = user ? actionMeta(item) : { Icon: ShieldQuestion, title: 'Permission Configuration', label: 'Configure', tone: 'text-amber-500' }; const Icon = meta.Icon; const age = user ? pendingAge(item) : null; return <li key={item.id} className="border-t border-border first:border-t-0"><div className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={() => { setShowAll(false); setSelected(item) }} className="flex min-w-0 flex-1 items-start gap-2 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Icon className={cn('mt-0.5 size-3.5 shrink-0', meta.tone)} aria-hidden="true" /><span className="min-w-0"><span className="flex flex-wrap items-center gap-1.5"><span className="text-xs font-semibold">{meta.title}</span>{user && item.accountType && <span className="rounded-full border border-border bg-muted/80 px-1.5 py-0.5 text-[0.55rem] font-semibold uppercase tracking-[0.09em]">{item.accountType}</span>}{user && isPreviewItem(item) && <span className="rounded-full border border-primary/40 bg-primary/10 px-1.5 py-0.5 text-[0.55rem] font-semibold uppercase tracking-[0.09em] text-primary">Sample</span>}</span><span className="mt-0.5 block truncate text-[0.65rem] font-medium text-muted-foreground">{user ? item.email || item.user : item.name}</span>{age && <span className="mt-0.5 block text-[0.6rem] text-muted-foreground">{age}</span>}</span></button>{user ? item.status === 'completed' ? <span className="shrink-0 text-[0.6rem] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Completed</span> : <button type="button" onClick={(event) => { event.stopPropagation(); runAction(item) }} className="inline-flex w-full shrink-0 items-center justify-center rounded-md border border-primary/40 bg-primary/10 px-3 py-1.5 text-[0.6rem] font-semibold uppercase tracking-[0.1em] text-primary hover:bg-primary hover:text-primary-foreground sm:w-auto">{meta.label}</button> : <button type="button" onClick={(event) => { event.stopPropagation(); runAction(item) }} className="inline-flex w-full shrink-0 items-center justify-center rounded-md border border-primary/40 bg-primary/10 px-3 py-1.5 text-[0.6rem] font-semibold uppercase tracking-[0.1em] text-primary hover:bg-primary hover:text-primary-foreground sm:w-auto">{meta.label}</button>}</div></li> }
  return <>
    <section className="flex flex-col rounded-xl border border-border bg-card p-4 text-foreground shadow-sm sm:p-5"><div className="flex shrink-0 items-baseline justify-between gap-3"><h2 className="font-serif text-2xl font-medium leading-tight sm:text-3xl">Pending Actions</h2>{allItems.length > 0 && <button type="button" onClick={() => { setShowAll(true); setSearch('') }} className="text-[0.62rem] font-semibold uppercase tracking-[0.14em] text-primary hover:underline">View All ({allItems.length})</button>}</div>{allItems.length === 0 ? <p className="mt-4 text-xs italic text-muted-foreground">No pending administrative actions.</p> : <ul className="mt-3">{previewItems.map((item) => row(item))}</ul>}</section>
    {showAll && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-foreground/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="pending-actions-title" onClick={() => setShowAll(false)}><div className="flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl bg-card shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex shrink-0 items-start justify-between border-b border-border px-5 py-4"><div><p className="text-[0.58rem] font-semibold uppercase tracking-[0.2em] text-muted-foreground">Administrative queue</p><h2 id="pending-actions-title" className="mt-1 font-serif text-xl font-medium">Pending Actions</h2><p className="mt-1 text-xs text-muted-foreground">{allItems.length} actions require administrative attention.</p></div><button type="button" onClick={() => setShowAll(false)} className="flex size-10 items-center justify-center rounded-lg text-muted-foreground hover:text-foreground" aria-label="Close pending actions"><X className="size-5" /></button></div><div className="border-b border-border p-4"><label className="relative block"><span className="sr-only">Search pending actions</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search pending actions..." className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm text-foreground outline-none focus:border-primary" /></label></div><ul className="min-h-0 overflow-y-auto px-4">{filteredItems.length ? filteredItems.map((item) => row(item)) : <li className="py-10 text-center text-sm text-muted-foreground">No pending actions match your search.</li>}</ul></div></div>}
    {selected && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-foreground/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="pending-action-title" onClick={() => setSelected(null)}><div className="w-full max-w-md rounded-xl bg-card shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-border px-5 py-4"><div><p className="text-[0.58rem] font-semibold uppercase tracking-[0.2em] text-muted-foreground">Pending Action Details</p><h2 id="pending-action-title" className="mt-1 font-serif text-xl font-medium">{isUserAction(selected) ? actionMeta(selected).title : 'Permission Configuration'}</h2></div><button type="button" onClick={() => setSelected(null)} className="flex size-10 items-center justify-center rounded-lg text-muted-foreground" aria-label="Close details"><X className="size-5" /></button></div><dl className="flex flex-col gap-3 px-5 py-5 text-sm"><div><dt className="text-[0.6rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Affected Account</dt><dd className="break-words">{isUserAction(selected) ? selected.email || selected.user : selected.name}</dd></div><div><dt className="text-[0.6rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Role</dt><dd>{isUserAction(selected) ? selected.accountType || 'Not provided' : selected.parentName}</dd></div><div><dt className="text-[0.6rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Status</dt><dd className="capitalize">{isUserAction(selected) ? selected.status : 'Pending'}{isPreviewItem(selected) && <span className="ml-2 text-xs text-primary">Sample / Preview</span>}</dd></div></dl><div className="flex justify-end gap-3 border-t border-border px-5 py-4"><button type="button" onClick={() => setSelected(null)} className="rounded-md border border-input px-4 py-2.5 text-[0.65rem] font-semibold uppercase tracking-[0.1em]">Close</button>{(isUserAction(selected) ? selected.status !== 'completed' : Boolean(onConfigureSubRole)) && <button type="button" onClick={() => runAction(selected)} className="rounded-md bg-primary px-4 py-2.5 text-[0.65rem] font-semibold uppercase tracking-[0.1em] text-primary-foreground">{isUserAction(selected) ? actionMeta(selected).label : 'Configure'}</button>}</div></div></div>}
  </>
}

export default AdminPendingActions
